create table projects(
	id bigint generated by default as identity primary key,
	name varchar(150) not null,
	description text,
	owner_id bigint not null,
	archived boolean not null default false,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now(),
	
	constraint fk_projects_owner foreign key (owner_id) references users (id)
);

 create table project_members(
 	id bigint generated by default as identity primary key,
 	project_id bigint not null,
 	user_id bigint not null,
 	role varchar(20) not null,
 	created_at timestamptz not null default now(),
 	updated_at timestamptz not null default now(),
 	
 	constraint fk_member_project foreign key (project_id) references projects (id) on delete cascade,
 	constraint fk_member_user foreign key (user_id) references users (id) on delete cascade,
 	constraint uq_members_project_user unique (project_id, user_id),
 	constraint ck_members_role check (role in ('OWNER', 'MANAGER', 'MEMBER'))
 );
 
 create index idx_members_user on project_members (user_id);