create table tasks(
	id bigint generated by default as identity primary key,
	project_id bigint not null,
	title varchar(200) not null,
	description text,
	status varchar(20) not null default 'TODO',
	priority varchar(20) not null default 'MEDIUM',
	assignee_id bigint,
	created_by bigint not null,
	due_date date,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now(),
	
	constraint fk_tasks_project foreign key (project_id) references projects (id) on delete cascade,
	constraint fk_tasks_assignee foreign key (assignee_id) references users (id) on delete set null,
	constraint fk_task_creator foreign key (created_by) references users (id),
	
	constraint ck_tasks_status check (status in ('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE')),
	constraint ck_tasks_priority check (priority in ('LOW', 'MEDIUM', 'HIGH', 'URGENT'))
);

create index idx_tasks_project_status on tasks (project_id, status);
create index idx_tasks_assignee on tasks (assignee_id);
create index idx_tasks_due_date on tasks (due_date);