create table refresh_tokens(
	id bigint generated by default as identity primary key,
	user_id bigint not null,
	token_hash varchar(64) not null,
	expires_at timestamptz not null,
	revoked_at timestamptz,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now(),
	
	constraint fk_refresh_user foreign key (user_id) references users (id) on delete cascade,
	constraint uq_refresh_token_hash unique (token_hash)
);

create index idx_refresh_user on refresh_tokens (user_id);