create table project_invitations(
	 id bigint generated by default as identity primary key,
	 project_id bigint not null,
	 email varchar(255) not null,
	 role varchar(20) not null,
	 token varchar(64) not null,
	 status varchar(20) not null default 'PENDING',
	 invited_by bigint not null,
	 expires_at timestamptz not null,
	 created_at timestamptz not null default now(),
	 updated_at timestamptz not null default now(),
	 
	 constraint fk_invitations_project
	 	foreign key (project_id) references projects (id) on delete cascade,
	 constraint fk_invitations_inviter
	 	foreign key (invited_by) references users (id),
	 	
	 constraint uq_invitations_token unique (token),
	 constraint ck_invitations_role check (role in ('MANAGER', 'MEMBER')),
	 constraint ck_invitations_status check (status in ('PENDING', 'ACCEPTED', 'EXPIRED'))
);

create index idx_invitation_project_email
	on project_invitations (project_id,lower(email));